// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd4hMfj7zMpN8dUOKX4cYYa0rC1u5G7jc',
    appId: '1:59704294952:web:c1f8e9da18c5d11bb2ff1d',
    messagingSenderId: '59704294952',
    projectId: 'authentication-127d9',
    authDomain: 'authentication-127d9.firebaseapp.com',
    storageBucket: 'authentication-127d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiBYrZmvXYhlrpGJKDEZRTx29hkih7I1Y',
    appId: '1:59704294952:android:8211f8b9a61bf406b2ff1d',
    messagingSenderId: '59704294952',
    projectId: 'authentication-127d9',
    storageBucket: 'authentication-127d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmZTHWdANzkvXR9Z1uQJA_3JNuQvGWRBE',
    appId: '1:59704294952:ios:aa1b044c6fcbee60b2ff1d',
    messagingSenderId: '59704294952',
    projectId: 'authentication-127d9',
    storageBucket: 'authentication-127d9.appspot.com',
    iosClientId: '59704294952-vlbepk4ksgfa4vip6fh4rtb0jbdcr4u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment1temp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmZTHWdANzkvXR9Z1uQJA_3JNuQvGWRBE',
    appId: '1:59704294952:ios:aa1b044c6fcbee60b2ff1d',
    messagingSenderId: '59704294952',
    projectId: 'authentication-127d9',
    storageBucket: 'authentication-127d9.appspot.com',
    iosClientId: '59704294952-vlbepk4ksgfa4vip6fh4rtb0jbdcr4u0.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment1temp',
  );
}
